meegloo/streams/urls.py
#!/usr/bin/env python
# encoding: utf-8

from django.conf.urls.defaults import *

urlpatterns = patterns('meegloo.streams.views',
	url(r'^$', 'posts', name = 'posts'),
	url(r'^feed\.rss$', 'posts', {'format': 'rss'}, name = 'user_rss'),
	url(r'^feed\.atom$', 'posts', {'format': 'atom'}, name = 'user_atom'),
	url(r'^streams\.js$', 'my_streams', name = 'streams_json'),
	url(r'^create/$', 'create', name = 'create_stream'),
	url(r'^join/$', 'streams', name = 'streams'),
	url(r'^categories/(?P<category>[\/\w-]+)/$', 'posts', name = 'category_posts'),
	url(r'^(?P<slug>[\w-]+)/join/$', 'join', name = 'join_stream'),
	url(r'^(?P<slug>[\w-]+)/edit/$', 'edit', name = 'edit_stream'),
	url(r'^(?P<slug>[\w-]+)/leave/$', 'leave', name = 'leave_stream'),
	url(r'^(?P<stream>[\w-]+)/$', 'posts', name = 'stream'),
	url(r'^(?P<stream>[\w-]+)/embed\.js$', 'posts', {'format': 'embed'}, name = 'embed_stream'),
	url(r'^(?P<stream>[\w-]+)/embed\.html$', 'posts', {'format': 'iframe'}, name = 'embed_stream'),
	url(r'^(?P<stream>[\w-]+)/feed\.rss$', 'posts', {'format': 'rss'}, name = 'stream_rss'),
	url(r'^(?P<stream>[\w-]+)/feed\.atom$', 'posts', {'format': 'atom'}, name = 'stream_atom'),
	url(r'^(?P<slug>[\w-]+)/embed/$', 'embed', name = 'embed_stream_options'),
	url(r'^(?P<stream>[\w-]+)/(?P<kind>audio|video|photo|text)/$', 'posts', name = 'stream_by_type'),
	url(r'^(?P<stream>[\w-]+)/(?P<kind>audio|video|photo|text)/feed\.rss$', 'posts', name = 'stream_by_type_rss'),
	url(r'^(?P<stream>[\w-]+)/posts/(?P<pk>\d+)/$', 'post', name = 'stream_post'),
	url(r'^(?P<stream>[\w-]+)/posts/(?P<pk>\d+)/embed/$', 'post', {'format': 'embed'}, name = 'embed_post'),
	url(r'^(?P<stream>[\w-]+)/sets/(?P<pk>\d+)/$', 'set', name = 'stream_set')
)

meegloo/urls.py
#!/usr/bin/env python
# encoding: utf-8

from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'^api/', include('meegloo.api.urls')),
	url(r'^uploadify/', include('meegloo.uploadify.urls')),
	url(r'^oembed/', include('meegloo.oembed.urls')),
	url(r'^about/$', 'django.views.generic.simple.direct_to_template',
		{
			'template': 'pages/about.html',
			'extra_context': {
				'body_classes': ('about', 'page'),
				'title_parts': ('About Meegloo',)
			}
		}, name = 'about'
	),
	url(r'^about/streams/$', 'django.views.generic.simple.direct_to_template',
		{
			'template': 'pages/streams.html',
			'extra_context': {
				'body_classes': ('about-streams', 'about', 'page'),
				'title_parts': ('Streams', 'About Meegloo',)
			}
		}, name = 'about_streams'
	),
	url(r'^about/networks/$', 'django.views.generic.simple.direct_to_template',
		{
			'template': 'pages/networks.html',
			'extra_context': {
				'body_classes': ('about-networks', 'about', 'page'),
				'title_parts': ('Networks', 'About Meegloo',)
			}
		}, name = 'about_networks'
	),
	url(r'^badges/$', 'django.views.generic.simple.direct_to_template',
		{
			'template': 'pages/badges.html',
			'extra_context': {
				'body_classes': ('badges', 'page'),
				'title_parts': ('Badges',)
			}
		}, name = 'badges'
	),
	url(r'^downloads/$', 'django.views.generic.simple.direct_to_template',
		{
			'template': 'pages/downloads.html',
			'extra_context': {
				'body_classes': ('downloads', 'page'),
				'title_parts': ('Downloads',)
			}
		}, name = 'downloads'
	),
	url(r'^terms/$', 'django.views.generic.simple.direct_to_template',
		{
			'template': 'pages/terms.html',
			'extra_context': {
				'body_classes': ('terms', 'page'),
				'title_parts': ('Terms and conditions',)
			}
		}, name = 'terms'
	),
	url(r'^privacy/$', 'django.views.generic.simple.direct_to_template',
		{
			'template': 'pages/privacy.html',
			'extra_context': {
				'body_classes': ('privacy', 'page'),
				'title_parts': ('Privacy policy',)
			}
		}, name = 'privacy'
	),
	url(r'^terms/mobile/$', 'django.views.generic.simple.direct_to_template',
		{
			'template': 'pages/terms.mobile.html'
		}, name = 'terms_mobile'
	),
	url(r'^social/', include('meegloo.social.urls')),
	url(r'^mail/', include('meegloo.mail.urls')),
	url(r'^', include('meegloo.viral.urls')),
	url(r'^', include('meegloo.core.urls')),
	url(r'^', include('meegloo.registration.urls')),
	url(r'^', include('meegloo.networks.urls')),
	url(r'^', include('meegloo.streams.urls'))
)

if getattr(settings, 'DEBUG', False):
	urlpatterns += patterns('django.views.static',
		(r'^media/(?P<path>.+)$', 'serve',
			{
				'document_root': getattr(settings, 'MEDIA_ROOT')
			}
		)
	)
	
	urlpatterns += patterns('django.views.generic.simple',
		(r'404\.html$', 'direct_to_template',
			{
				'template': '404.html'
			}
		)
	)
	
	urlpatterns += patterns('django.views.generic.simple',
		(r'500\.html$', 'direct_to_template',
			{
				'template': '500.html'
			}
		)
	)

meegloo/streams/models.py
#!/usr/bin/env python
# encoding: utf-8

from django.db import models
from django.contrib.contenttypes import generic
from django.core.exceptions import ValidationError
from meegloo.streams import POST_TYPES, POST_STATES, POST_LIVE, POST_CONVERTING, helpers, managers
from taggit.managers import TaggableManager
import logging

class Category(models.Model):
	name = models.CharField(max_length = 50)
	slug = models.SlugField(max_length = 50)
	parent = models.ForeignKey('self', null = True)
	
	def __unicode__(self):
		return self.name
	
	class Meta:
		ordering = ('name',)

class Stream(models.Model):
	name = models.CharField(max_length = 50)
	slug = models.SlugField(max_length = 20)
	network = models.ForeignKey('networks.Network', related_name = 'streams')
	description = models.CharField(max_length = 200, null = True, blank = True)
	category = models.ForeignKey('Category', related_name = 'streams', default = 5)
	start = models.DateTimeField(auto_now_add = True)
	end = models.DateTimeField(null = True, blank = True)
	updated = models.DateTimeField(auto_now_add = True)
	objects = managers.StreamManager()
	
	def clean(self):
		from django.conf import settings
		import re
		
		if not re.match(r'^[\w-]+$', self.slug):
			raise ValidationError('Enter a valid slug.')
		
		if self.slug in getattr(settings, 'INVALID_SLUGS', []):
			raise ValidationError('%s is not a valid stream URL.' % self.slug)
	
	def latest_post(self):
		return Post.objects.filter(
			stream__part_of = self,
			stream__private = False
		).latest()
	
	def __unicode__(self):
		return self.name
	
	def get_full_base_url(self):
		return 'http://%s%s' % (self.network.domain, self.get_absolute_url())
	
	def get_embed_code(self, base_url = None):
		if not base_url:
			base_url = self.get_full_base_url()
		
		from django.core.urlresolvers import reverse
		return '<script src="%sembed.js"></script>' % base_url
	
	def save(self, *args, **kwargs):
		from datetime import datetime, timedelta
		
		if self.updated:
			self.end = self.updated + timedelta(days = 1)
		else:
			self.end = datetime.now() + timedelta(days = 1)
		
		super(Stream, self).save(*args, **kwargs)
	
	def get_twitter_tags(self, author = None):
		tags = StreamTag.objects.filter(
			stream = self,
			domain = 'twitter.com'
		)
		
		if author:
			tags = tags.filter(user = author)
		
		return tags.values_list('tag', flat = True)
	
	def update_twitter(self, author):
		from django.conf import settings
		from meegloo.core.models import OAuthToken
		from meegloo.urlshortening.helpers import shorten
		from meegloo.social.helpers import format_tweet
		from twitter import Api
		
		oauth_creds = getattr(settings, 'OAUTH_CREDENTIALS').get('TWITTER')
		logger = logging.getLogger()
		
		api = Api(
			consumer_key = oauth_creds.get('CONSUMER_KEY'),
			consumer_secret = oauth_creds.get('CONSUMER_SECRET'),
			access_token_key = oauth_creds.get('BOT_TOKEN'),
			access_token_secret = oauth_creds.get('BOT_SECRET')
		)
		
		try:
			username = '@' + author.oauth_tokens.get(site = 'twitter').username
		except OAuthToken.DoesNotExist:
			username = author.get_full_name() or author.username
		
		tags = self.get_twitter_tags(author)
		url = shorten(self, self.network, author)
		text = '%s - Covered by %s' % (self.name, username)
		tweet = format_tweet(text, tags, url)
		
		try:
			api.PostUpdate(tweet)
		except Exception, ex:
			logger.error('Unable to post tweet', exc_info = ex)
	
	@models.permalink
	def get_absolute_url(self):
		return ('stream', [self.slug])
	
	class Meta:
		ordering = ('-updated',)
		get_latest_by = 'updated'
	
	class QuerySet(models.query.QuerySet):
		def public(self):
			return self.filter(
				pk__in = UserStream.objects.public().values_list('part_of__pk')
			).extra(
				where = (
					'(SELECT COUNT(*) FROM `%(Post)s` INNER JOIN ' \
					'`%(UserStream)s` ON `%(UserStream)s`.`id` = `%(Post)s`.`stream_id` WHERE ' \
					'`%(UserStream)s`.`private` = 0 AND `%(UserStream)s`.`part_of_id` = ' \
					'`%(Stream)s`.`id`) > 0' % {
						'Post': Post._meta.db_table,
						'UserStream': UserStream._meta.db_table,
						'Stream': Stream._meta.db_table
					},
				)
			)
		
		def summary(self):
			return self.extra(
				select = {
					'post_count': 'SELECT COUNT(*) FROM `%(Post)s` INNER JOIN ' \
						'`%(UserStream)s` ON `%(UserStream)s`.`id` = `%(Post)s`.`stream_id` WHERE ' \
						'`%(UserStream)s`.`private` = 0 AND `%(UserStream)s`.`part_of_id` = ' \
						'`%(Stream)s`.`id`' % {
							'Post': Post._meta.db_table,
							'UserStream': UserStream._meta.db_table,
							'Stream': Stream._meta.db_table
						},
					'contributor_count': 'SELECT COUNT(*) FROM `%(UserStream)s` WHERE ' \
						'`%(UserStream)s`.`private` = 0 AND `%(UserStream)s`.`part_of_id` = ' \
						'`%(Stream)s`.`id`' % {
							'UserStream': UserStream._meta.db_table,
							'Stream': Stream._meta.db_table
						}
				}
			)
		
		def near(self, latitude, longitude):
			sql = """(SELECT COUNT(*) FROM `%(Post)s` INNER JOIN `%(UserStream)s` ON
			`%(Post)s`.`stream_id` = `%(UserStream)s`.`id` WHERE ((ACOS(SIN(%(latitude)s * PI() /
			180) * SIN(`%(Post)s`.`latitude` * PI() / 180) + COS(%(latitude)s * PI() / 180) *
			COS(`%(Post)s`.`latitude` * PI() / 180) * COS((%(longitude)s - 
			`%(Post)s`.`longitude`) * PI() / 180)) * 180 / PI()) * 60 * 1.1515) <= 10 AND
			`%(UserStream)s`.`part_of_id` = `%(Stream)s`.`id`)""" % {
				'latitude': latitude,
				'longitude': longitude,
				'Post': Post._meta.db_table,
				'Stream': self.model._meta.db_table,
				'UserStream': UserStream._meta.db_table
			}
			
			qs = self.exclude(
				contributors__posts__latitude = '',
				contributors__posts__longitude = '',
				contributors__posts__latitude__isnull = True,
				contributors__posts__longitude__isnull = True
			).extra(
				where = [
					'%s <= 5' % sql
				]
			)
			
			return qs

class StreamTag(models.Model):
	stream = models.ForeignKey('Stream', related_name = 'tags')
	user = models.ForeignKey('auth.User', related_name = 'stream_tags', null = True)
	domain = models.CharField(max_length = 100)
	tag = models.CharField(max_length = 30)
	
	def __unicode__(self):
		return self.tag
	
	class Meta:
		db_table = 'streams_stream_tag'
		unique_together = ('stream', 'user', 'domain', 'tag')

class UserStream(models.Model):
	part_of = models.ForeignKey('Stream', related_name = 'contributors')
	private = models.BooleanField()
	profile = models.ForeignKey('auth.User', related_name = 'streams')
	updated = models.DateTimeField(auto_now_add = True, auto_now = True)
	objects = managers.UserStreamManager()
	
	def __unicode__(self):
		return unicode(self.part_of)
	
	def get_absolute_url(self):
		return self.part_of.get_absolute_url()
	
	def get_full_base_url(self):
		return 'http://%s.%s%s' % (
			self.profile.username,
			self.part_of.network.domain,
			self.get_absolute_url()
		)
	
	def get_embed_code(self):
		return self.part_of.get_embed_code(
			self.get_full_base_url()
		)
	
	def save(self, *args, **kwargs):
		super(UserStream, self).save(*args, **kwargs)
		self.part_of.updated = self.updated
		self.part_of.save()
	
	class QuerySet(models.query.QuerySet):
		def near(self, latitude, longitude):
			sql = """(SELECT COUNT(*) FROM `%(Post)s` WHERE ((ACOS(SIN(%(latitude)s * PI() /
			180) * SIN(`%(Post)s`.`latitude` * PI() / 180) + COS(%(latitude)s * PI() / 180) *
			COS(`%(Post)s`.`latitude` * PI() / 180) * COS((%(longitude)s - 
			`%(Post)s`.`longitude`) * PI() / 180)) * 180 / PI()) * 60 * 1.1515) <= 1 AND
			`%(Post)s`.`stream_id` = `%(UserStream)s`.`id`)""" % {
				'latitude': latitude,
				'longitude': longitude,
				'Post': Post._meta.db_table,
				'UserStream': self.model._meta.db_table
			}
			
			qs = self.exclude(
				posts__latitude = '',
				posts__longitude = '',
				posts__latitude__isnull = True,
				posts__longitude__isnull = True
			).extra(
				where = [
					'%s <= 5' % sql
				]
			)
			
			return qs
		
		def live(self):
			return self.filter(posts__state = 2)
			
		def public(self):
			return self.filter(private = False)
		
		def summary(self):
			return self.extra(
				select = {
					'post_count': 'SELECT COUNT(*) FROM `%(Post)s` WHERE ' \
						'`%(Post)s`.`stream_id` = `%(UserStream)s`.`id`'  % {
							'Post': Post._meta.db_table,
							'UserStream': UserStream._meta.db_table,
						}
				}
			)
	
	class Meta:
		db_table = 'streams_stream_user'
		ordering = ('-updated',)
		get_latest_by = 'updated'
		verbose_name = 'contributor'

class StreamEmbed(models.Model):
	stream = models.ForeignKey('UserStream', related_name = 'embeds')
	domain = models.CharField(max_length = 100)
	
	def __unicode__(self):
		return self.domain
	
	class Meta:
		db_table = 'streams_stream_embed'
		ordering = ('domain',)
		unique_together = ('stream', 'domain')

class Post(models.Model):
	stream = models.ForeignKey('UserStream', related_name = 'posts')
	posted = models.DateTimeField()
	kind = models.CharField(max_length = 10, choices = POST_TYPES)
	text = models.CharField(max_length = 200, null = True, blank = True)
	tags = TaggableManager()
	author = models.ForeignKey('auth.User', null = True, blank = True, related_name = 'posts')
	application = models.ForeignKey('piston.Consumer',
		null = True, blank = True, related_name = 'posts', editable = False
	)
	latitude = models.CharField(max_length = 30, null = True, blank = True)
	longitude = models.CharField(max_length = 30, null = True, blank = True)
	area = models.CharField(max_length = 50, null = True, blank = True)
	tweet = models.BooleanField()
	state = models.IntegerField(choices = POST_STATES, default = POST_LIVE)
	guid = models.CharField(max_length = 36, unique = True, null = True, blank = True)
	comments = generic.GenericRelation('social.Comment')
	objects = managers.PostManager()
	
	@property
	def html_template_name(self):
		return 'posts/%s.inc.html' % self.kind
	
	@property
	def js_template_name(self):
		return 'posts/%s.inc.js' % self.kind
	
	def __unicode__(self):
		return unicode(self.text)
	

templates/streams/avatar.inc.html
{% load gravatar %}

<div class="avatar">
	<a href="http://{{ request.profile.username }}.{{ request.network.domain }}">
		<img src="{{ request.profile.email|gravatar:100 }}" />
		<span>{{ request.profile.get_full_name|default:request.profile.username }}</span>
	</a>
</div>

templates/streams/create.html
{% extends 'base.html' %}
{% load i18n markup %}

{% block content %}
	{% block headline %}
		<h1>Create a new stream</h1>
	{% endblock %}
	
	<article class="page">
		{% if not form.errors %}
			<p>
				Here&rsquo;s where you start telling your story. Give your new
				stream a name, fill in the tags and you&rsquo;re ready to go.
			</p>
		{% endif %}
		
		{% if alt_streams %}
			<div class="stream-list">
				<h2>Someone might be covering the same story</h2>
				<p>
					We&rsquo;ve matched up other events with similar details. If you find one that
					matches the stream you&rsquo;re creating, just click it and you can start adding
					to their story. 
				</p>
				
				{% for stream in alt_streams %}
					<a class="stream" href="{% url join_stream stream.slug %}">
						<h3>{{ stream.name }}</h3>
						
						{% if stream.description %}
							{{ stream.description|markdown }}
						{% endif %}
						
						<p class="stream-meta">
							Updated {{ stream.updated|timesince }} ago{% spaceless %}
							{% if stream.tags.count > 0 %}, tagged
								{{ stream.tags.all|join:', ' }}
							{% endif %}
						{% endspaceless %}</p>
					</a>
				{% endfor %}
				
				<div class="clear"></div>
				
				<p>
					If you can&rsquo;t find a stream that matches yours, you can continue creating it
					with a different URL (so that we don&rsquo;t confuse it with other streams).
				</p>
			
				<p><a class="button" href="#continue">Continue creating my stream</a></p>
			</div>
		{% endif %}
		
		<form action="{{ request.path }}{% if request.META.QUERY_STRING %}?{{ request.META.QUERY_STRING }}{% endif %}" method="post">
			{% if form.errors %}
				<p>Whoops! Sorry, it looks like something&rsquo;s not quite right.</p>
				
				{% if form.non_field_errors %}
					<p class="error-header">{{ form.non_field_errors|join:'<br />' }}</p>
				{% endif %}
			{% endif %}
			
			{% for field in form %}
				<div class="form-field">
					<div class="module label">
						<label for="id_{{ field.html_name }}">{{ field.label }}</label><br />
						{% if field.errors %}
							<span class="errors">{{ field.errors }}</span>
						{% else %}
							<span class="help-text">{{ field.help_text }}</span>
						{% endif %}
					</div>
					
					<div class="module field">
						{{ field }}
					</div>
				</div>
			{% endfor %}
			
			{% csrf_token %}
			<div class="module submit">
				<input type="submit" value="{% ifequal request.method 'POST' %}Try again{% else %}Create my stream!{% endifequal %}" />
			</div>
			
			<div class="clear"></div>
		</form>
	</article>
{% endblock content %}

{% block sidebar %}
	<article class="module latest-streams">
		<h2>The latest streams</h2>
		<p>These are the latest streams people have created. Why not join one of these?</p>
		
		{% for stream in latest_streams %}
			<a class="stream" href="{% url stream stream.slug %}">
				<h3>{{ stream.name }}</h3>
				
				<p class="stream-meta">
					Updated {{ stream.updated|timesince }} ago{% spaceless %}
					{% if stream.tags.count > 0 %}, tagged
						{{ stream.tags.all|join:', ' }}
					{% endif %}
				{% endspaceless %}</p>
			</a>
		{% endfor %}
	</article>
	
	{{ block.super }}
{% endblock sidebar %}

{% block javascript %}
	{{ block.super }}
	<script>
		$(document).ready(
			function() {
				$('#id_name').bind('keypress',
					function(e) {
						setTimeout(
							function() {
								$('#id_slug').val(
									URLify($('#id_name').val())
								);
							},
							10
						)
					}
				);
				
				$('#id_name').bind('change',
					function(e) {
						$('#id_slug').val(
							URLify($(this).val())
						);
					}
				);
				
				$('#id_slug').bind('change',
					function(e) {
						$(this).val(
							URLify($(this).val())
						);
					}
				);
				
				$('#id_slug').bind('blur',
					function(e) {
						if($(this).val()) {
							$('#id_twitter_hashtag').val('#' + $(this).val());
							$('#id_flickr_tag').val($(this).val());
						} else {
							$('#id_twitter_hashtag').val('');
							$('#id_flickr_tag').val('');
						}
					}
				);
				
				$(window).hashchange(
					function() {
						if(window.location.hash == '#continue') {
							$('.stream-list').slideUp(
								function() {
									$('form').slideDown();
									$('form #id_slug').focus();
								}
							);
						}
					}
				);
				
				if(window.location.hash == '#continue') {
					$('.stream-list').slideUp(
						function() {
							$('form').slideDown();
							$('form #id_slug').focus();
						}
					);
				}
			}
		);
	</script>
{% endblock javascript %}

templates/streams/edit.html
{% extends 'base.html' %}
{% load i18n markup %}

{% block content %}
	{% block headline %}
		<h1>{{ stream.part_of.name }}</h1>
	{% endblock %}
	
	<article class="page">
		{% if not form.errors %}
			<p>
				You can make a few basic changes to your stream here.
			</p>
		{% endif %}
		
		<form action="{{ request.path }}{% if request.META.QUERY_STRING %}?{{ request.META.QUERY_STRING }}{% endif %}" method="post">
			{% if form.errors %}
				<p>Whoops! Sorry, it looks like something&rsquo;s not quite right.</p>
				
				{% if form.non_field_errors %}
					<p class="error-header">{{ form.non_field_errors|join:'<br />' }}</p>
				{% endif %}
			{% else %}
				{% if stream.part_of.contributors.count > 1 %}
					<p class="info-header">
						Because other people are part of this stream, it&rsquo;s not possible to
						change the name, URL or description.
					</p>
				{% endif %}
			{% endif %}
			
			{% for field in form %}
				{% ifequal field.name 'twitter_hashtag' %}
					<p>Changes you make here won&rsquo;t affect other contributors to the stream.</p>
				{% endifequal %}
				
				<div class="form-field">
					<div class="module label">
						<label for="id_{{ field.html_name }}">{{ field.label }}</label><br />
						{% if field.errors %}
							<span class="errors">{{ field.errors }}</span>
						{% else %}
							<span class="help-text">{{ field.help_text }}</span>
						{% endif %}
					</div>
					
					<div class="module field">
						{{ field }}
					</div>
				</div>
			{% endfor %}
			
			{% csrf_token %}
			
			<div class="module leave">
				<a class="button" href="{% url leave_stream stream.part_of.slug %}">Leave this stream</a>
			</div>
			
			<div class="module submit">
				<input type="submit" value="{% ifequal request.method 'POST' %}Try again{% else %}Update my stream!{% endifequal %}" />
			</div>
			
			<div class="clear"></div>
		</form>
	</article>
{% endblock content %}

{% block sidebar %}
	{% include 'streams/sidebar.inc.html' %}
{% endblock sidebar %}

{% block javascript %}
	{{ block.super }}
	<script>
		$(document).ready(
			function() {
				$('#id_name').bind('keypress',
					function(e) {
						setTimeout(
							function() {
								$('#id_slug').val(
									URLify($('#id_name').val())
								);
							},
							10
						)
					}
				);
				
				$('#id_name').bind('change',
					function(e) {
						$('#id_slug').val(
							URLify($(this).val())
						);
					}
				);
				
				$('#id_slug').bind('change',
					function(e) {
						$(this).val(
							URLify($(this).val())
						);
					}
				);
				
				$('#id_slug').bind('blur',
					function(e) {
						if($(this).val()) {
							$('#id_twitter_hashtag').val('#' + $(this).val());
							$('#id_flickr_tag').val($(this).val());
						} else {
							$('#id_twitter_hashtag').val('');
							$('#id_flickr_tag').val('');
						}
					}
				);
				
				$(window).hashchange(
					function() {
						if(window.location.hash == '#continue') {
							$('.stream-list').slideUp(
								function() {
									$('form').slideDown();
									$('form #id_slug').focus();
								}
							);
						}
					}
				);
				
				if(window.location.hash == '#continue') {
					$('.stream-list').slideUp(
						function() {
							$('form').slideDown();
							$('form #id_slug').focus();
						}
					);
				}
			}
		);
	</script>
{% endblock javascript %}

templates/streams/post.embed.html
<DOCTYPE html>
<html>
	<head>
		<style>
			body {
				margin: 0; padding: 0;
			}
		</style>
		
		<script src="{{ MEDIA_URL }}js/jquery.js"></script>
		<script src="{{ MEDIA_URL }}js/jwplayer/jwplayer.js"></script>
	</head>
	<body>
		<div id="post-{{ post.pk }}"></div>
		
		<script>
			$(document).ready(
				function() {
					{% include post.js_template_name %}
				}
			);
		</script>
	</body>
</html>

templates/streams/post.html
{% extends 'base.html' %}
{% load i18n %}

{% block extra_head %}
	{{ block.super }}
	
	<link rel="alternate" type="application/atom+xml" title="Subscribe to posts in your feed reader" href="../../feed.atom" />
{% endblock %}

{% block content %}
	<h1><a href="{{ stream.get_absolute_url }}">{{ stream }}</a></h1>
	
	{% if request.user.is_anonymous %}
		<article id="welcome">
			<p class="first">{% spaceless %}
				{{ stream.profile.first_name|default:stream.profile.username }} is
				using Meegloo to share {% ifequal post.kind 'photo' %}a {% endifequal %}
				{{ post.get_kind_display }} about {{ stream }}.
				You can use Meegloo to share content about the topics
				that are important to you. <a href="http://meegloo.com{% url register %}">Sign up now &raquo;</a>
			{% endspaceless %}</p>
			
			<p>{% spaceless %}
				<a href="http://{{ stream.profile.username }}.{{ request.network.domain }}{{ stream.get_absolute_url }}">See more of
				{{ stream.profile.first_name|default:stream.profile.username }}&rsquo;s coverage of
				{{ stream }}</a>
			{% endspaceless %}</p>
			
			<div class="clear"></div>
		</article>
	{% endif %}
	
	<section class="page">
		{% include 'social/sharethis.inc.html' %}
	</section>
	
	<section class="posts">
		{% include post.html_template_name with single='True' %}
		{% include 'social/comments.inc.html' with obj=post %}
	</section>
{% endblock content %}

{% block sidebar %}
	{% include 'streams/sidebar.inc.html' %}
{% endblock sidebar %}

{% block javascript %}
	{{ block.super }}
	<script src="{{ MEDIA_URL }}js/jwplayer/jwplayer.js"></script>
	
	<script>
		$(document).ready(
			function() {
				{% include post.js_template_name %}
			}
		);
	</script>
{% endblock javascript %}